/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MontarLookRouteImport } from './routes/montar-look'
import { Route as EstiloRouteImport } from './routes/estilo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'

const MontarLookRoute = MontarLookRouteImport.update({
  id: '/montar-look',
  path: '/montar-look',
  getParentRoute: () => rootRouteImport,
} as any)
const EstiloRoute = EstiloRouteImport.update({
  id: '/estilo',
  path: '/estilo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/estilo': typeof EstiloRoute
  '/montar-look': typeof MontarLookRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/estilo': typeof EstiloRoute
  '/montar-look': typeof MontarLookRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/estilo': typeof EstiloRoute
  '/montar-look': typeof MontarLookRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/estilo'
    | '/montar-look'
    | '/colecao/$slug'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/estilo'
    | '/montar-look'
    | '/colecao/$slug'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/estilo'
    | '/montar-look'
    | '/colecao/$slug'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  EstiloRoute: typeof EstiloRoute
  MontarLookRoute: typeof MontarLookRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/montar-look': {
      id: '/montar-look'
      path: '/montar-look'
      fullPath: '/montar-look'
      preLoaderRoute: typeof MontarLookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estilo': {
      id: '/estilo'
      path: '/estilo'
      fullPath: '/estilo'
      preLoaderRoute: typeof EstiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  EstiloRoute: EstiloRoute,
  MontarLookRoute: MontarLookRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
