/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MontarLookRouteImport } from './routes/montar-look'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EstiloRouteImport } from './routes/estilo'
import { Route as ConsultorRouteImport } from './routes/consultor'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MontarLookRoute = MontarLookRouteImport.update({
  id: '/montar-look',
  path: '/montar-look',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstiloRoute = EstiloRouteImport.update({
  id: '/estilo',
  path: '/estilo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorRoute = ConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/consultor': typeof ConsultorRoute
  '/estilo': typeof EstiloRoute
  '/favoritos': typeof FavoritosRoute
  '/montar-look': typeof MontarLookRoute
  '/sobre': typeof SobreRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/consultor': typeof ConsultorRoute
  '/estilo': typeof EstiloRoute
  '/favoritos': typeof FavoritosRoute
  '/montar-look': typeof MontarLookRoute
  '/sobre': typeof SobreRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/consultor': typeof ConsultorRoute
  '/estilo': typeof EstiloRoute
  '/favoritos': typeof FavoritosRoute
  '/montar-look': typeof MontarLookRoute
  '/sobre': typeof SobreRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/consultor'
    | '/estilo'
    | '/favoritos'
    | '/montar-look'
    | '/sobre'
    | '/colecao/$slug'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/consultor'
    | '/estilo'
    | '/favoritos'
    | '/montar-look'
    | '/sobre'
    | '/colecao/$slug'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/consultor'
    | '/estilo'
    | '/favoritos'
    | '/montar-look'
    | '/sobre'
    | '/colecao/$slug'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ConsultorRoute: typeof ConsultorRoute
  EstiloRoute: typeof EstiloRoute
  FavoritosRoute: typeof FavoritosRoute
  MontarLookRoute: typeof MontarLookRoute
  SobreRoute: typeof SobreRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montar-look': {
      id: '/montar-look'
      path: '/montar-look'
      fullPath: '/montar-look'
      preLoaderRoute: typeof MontarLookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estilo': {
      id: '/estilo'
      path: '/estilo'
      fullPath: '/estilo'
      preLoaderRoute: typeof EstiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor': {
      id: '/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof ConsultorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  ConsultorRoute: ConsultorRoute,
  EstiloRoute: EstiloRoute,
  FavoritosRoute: FavoritosRoute,
  MontarLookRoute: MontarLookRoute,
  SobreRoute: SobreRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
